"""Type information for indexgenerator.

Notes:
- Python types are used rather than C types whenever possible, e.g. c_size_t -> int.
- C types are used for element's type in Array since it affects data's layout and size.
- Docstrings for _FuncPtr are written here for now.
"""

from ctypes import c_uint, c_void_p
from ctypes import Array, _Pointer

from ._types import *

def generateVertexRemap(
    destination: _Pointer[c_uint] | Array[c_uint],
    indices: _Pointer[c_uint] | Array[c_uint],
    index_count: int,
    vertices: c_void_p,
    vertex_count: int,
    vertex_size: int,
) -> int:
    """Generates a vertex remap table from the vertex buffer and an optional
    index buffer and returns number of unique vertices

    As a result, all vertices that are binary equivalent map to the same (new)
    location, with no gaps in the resulting sequence.
    Resulting remap table maps old vertices to new vertices and can be used in
    meshopt_remapVertexBuffer/meshopt_remapIndexBuffer.
    Note that binary equivalence considers all vertex_size bytes, including padding
    which should be zero-initialized.

    destination must contain enough space for the resulting remap table (vertex_count elements)
    indices can be NULL if the input is unindexed
    """
    ...

def remapVertexBuffer(
    destination: c_void_p,
    vertices: c_void_p,
    vertex_count: int,
    vertex_size: int,
    remap: _Pointer[c_uint] | Array[c_uint],
) -> None:
    """Generates vertex buffer from the source vertex buffer and remap table
    generated by meshopt_generateVertexRemap

    destination must contain enough space for the resulting vertex buffer (unique_vertex_count elements, returned by meshopt_generateVertexRemap)
    vertex_count should be the initial vertex count and not the value returned by meshopt_generateVertexRemap
    """
    ...

def remapIndexBuffer(
    destination: _Pointer[c_uint] | Array[c_uint],
    indices: _Pointer[c_uint] | Array[c_uint],
    index_count: int,
    remap: _Pointer[c_uint] | Array[c_uint],
) -> None:
    """Generate index buffer from the source index buffer and remap table
    generated by meshopt_generateVertexRemap

    destination must contain enough space for the resulting index buffer (index_count elements)
    indices can be NULL if the input is unindexed
    """
    ...
